version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "jiremv"
github_repo = "serverless-stripe-checkout"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[serverless-stripe-checkout-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-serverles-PipelineExecutionRole-KD9VlzTMeXlh"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-serve-CloudFormationExecutionRo-ELbmYygqZJAA"
artifacts_bucket = "aws-sam-cli-managed-serverless-str-artifactsbucket-ybnudupemh9u"
image_repository = ""
region = "us-west-1"

[serverless-stripe-checkout-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-serverles-PipelineExecutionRole-WCWB2W1a6oCb"
cloudformation_execution_role = "arn:aws:iam::545200407638:role/aws-sam-cli-managed-serve-CloudFormationExecutionRo-Uz1d30qGw3S6"
artifacts_bucket = "aws-sam-cli-managed-serverless-str-artifactsbucket-mx0cgnmg1mck"
image_repository = ""
region = "us-west-2"
